services:
  mosquitto:
    container_name: ${MQTT_CONTAINER_NAME}
    image: eclipse-mosquitto
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - ${MQTT_PORT}:1883
      - ${MQTT_PORT2}:9001
